services:
  app:
    container_name: leorio_bot
    build:
      context: .
      dockerfile: dockerfile
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
    ports:
      - 80:80
